# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jumpdoor
tagline:             'Adventure begins'
description:         ''
url:                 http://notes.is9.co
baseurl:             /
paginate:            5

# About/contact
author:
  name:              jondb
  url:               https://www.jumpdoor.io
  email:             jon@jumpdoor.io

# Custom vars
version:             1.0.0
