# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               IS9
tagline:             'Information Security Notes'
description:         'Notes on information security.'
url:                 http://notes.is9.co
baseurl:             /
paginate:            5

# About/contact
author:
  name:              jondb
  url:               https://www.is9.co
  email:             jon@is9.co

# Custom vars
version:             1.0.0
